# IBM Data Science Capstone Project
*Opening a Mexican Restaurant in San Diego*

- Build a dataframe of cities in San Diego, CA through web-scraping and preprocessing
- Retrieve the geographical coordinates of each city
- Query venue data for each city by leveraging FourSquare API data
- Explore and cluster the cities using kmeans machine-learning algorithm
- Determine the best cluster to open a new Mexican Restaurant in San Diego

__1. Scrape the web and create a dataframe of San Diego cities.__

In [2]:
# Import dependencies

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from pandas import DataFrame

# Define html variable
html = "https://en.wikipedia.org/wiki/Category:Cities_in_San_Diego_County,_California"
contents = requests.get(html).text
# Define soup variable
soup = BeautifulSoup(contents, 'html.parser')
# Empty list to append cities
city_list = []

# # Need to parse through DOM to know which table to scrape
for row in soup.find_all("div", class_="mw-category")[1].findAll("li"):
    city_list.append(row.text)

df1 = pd.DataFrame({"City": city_list})
# All outputs are of the form 'City_Name, Californa'
# Only want city names! Use split function.
df1["City"] = df1["City"].str.split(",").str[0]
num_cities = df1.shape[0]

print("")
print(f'There are {num_cities} cities in the dataframe')
print("")
df1

There are 18 cities in the dataframe

              City
0         Carlsbad
1      Chula Vista
2         Coronado
3          Del Mar
4         El Cajon
5        Encinitas
6        Escondido
7   Imperial Beach
8          La Mesa
9      Lemon Grove
10   National City
11       Oceanside
12           Poway
13       San Diego
14      San Marcos
15          Santee
16    Solana Beach
17           Vista

In [4]:
import geopy
from geopy.geocoders import  Nominatim

geolocator = Nominatim(user_agent="sd_explorer")


lats = []
longs = []

for city in df1["City"]:
    address = city
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    lats.append(latitude)
    longs.append(longitude)

In [5]:
df1["Latitude"] = lats
df1["Longitude"] = longs

In [6]:
# Install and import folium as map rendering library
!conda install -c conda-forge folium=0.5.0 --yes
import folium

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# Import k-means from clustering stage from SciKit-Learn

from sklearn.cluster import KMeans

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    folium-0.5.0               |             py_0          45 KB  conda-forge
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    certifi-2020.6.20          |   py36h9f0ad1d_0         151 KB  conda-forge
    ca-certificates-2020.6.20  |       hecda079_0         145 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    openssl-1.1.1g             |       h516909a_1         2.1 MB  conda-forge
    branca-0.4.1               |             py_0          26 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

    altair:          4.1.0-py_1        conda-forge
    branca:          0.4.1-py_0        conda-forge
    folium:          0.5.0-py_0        conda-forge
    python_abi:      3.6-1_cp36m       conda-forge
    vincent:         0.4.4-py_1        conda-forge

The following packages will be UPDATED:

    certifi:         2020.6.20-py36_0              --> 2020.6.20-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0             --> 1.1.1g-h516909a_1        conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2020.6.24-0                   --> 2020.6.20-hecda079_0     conda-forge


Downloading and Extracting Packages
folium-0.5.0         | 45 KB     | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
certifi-2020.6.20    | 151 KB    | ##################################### | 100%
ca-certificates-2020 | 145 KB    | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
branca-0.4.1         | 26 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [7]:
address = 'San Diego, CA, USA'

geolocator = Nominatim(user_agent="sd_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of San Diego are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of San Diego are 32.7174209, -117.1627714.

In [8]:
# Both San Marcos and La Mesa are off the mark
la_mesa_lat = 32.772404
la_mesa_long = -117.029327
san_marcos_lat = 33.1350206
san_marcos_long = -117.17433

df1.loc[df1["City"] == "La Mesa", "Latitude"] = la_mesa_lat
df1.loc[df1["City"] == "La Mesa", "Longitude"] = la_mesa_long
df1.loc[df1["City"] == "San Marcos", "Latitude"] = san_marcos_lat
df1.loc[df1["City"] == "San Marcos", "Longitude"] = san_marcos_long
# What does the dataframe look like now?
df1

              City   Latitude   Longitude
0         Carlsbad  33.158093 -117.350597
1      Chula Vista  32.640054 -117.084196
2         Coronado  32.691520 -117.176695
3          Del Mar  32.959489 -117.265315
4         El Cajon  32.794773 -116.962527
5        Encinitas  33.036987 -117.291982
6        Escondido  33.121675 -117.081485
7   Imperial Beach  32.583944 -117.113085
8          La Mesa  32.772404 -117.029327
9      Lemon Grove  32.742552 -117.031417
10   National City  32.678109 -117.099197
11       Oceanside  33.195870 -117.379483
12           Poway  32.962823 -117.035865
13       San Diego  32.717421 -117.162771
14      San Marcos  33.135021 -117.174330
15          Santee  32.838383 -116.973917
16    Solana Beach  32.990560 -117.269132
17           Vista  33.200037 -117.242536

In [9]:
map_sd_1 = folium.Map(location=[latitude, longitude], zoom_start = 10)

# # add markers to map

sd_city = df1["City"]
sd_lat = df1["Latitude"]
sd_long = df1["Longitude"]

for lat, long, city in zip(sd_lat, sd_long, sd_city):
    label = '{}'.format(city)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, long],
        radius=5.3,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_sd_1)

map_sd_1

In [10]:
# The code was removed by Watson Studio for sharing.

In [11]:
# Defining a function to return venues within a 2000 meter radius of each city

def getNearbyVenues(names, latitudes, longitudes, radius=500, limit=100):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            client_id, 
            client_secret, 
            version, 
            lat, 
            lng, 
            radius, 
            limit)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['City', 
                  'City Latitude', 
                  'City Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [12]:
%%capture
sd_venues = getNearbyVenues(names=sd_city,
                                   latitudes=sd_lat,
                                   longitudes=sd_long
                                  )

In [13]:
print(f'There are {sd_venues.shape[0]} rows and {sd_venues.shape[1]} columns in the dataframe below')
sd_venues.head()

There are 681 rows and 7 columns in the dataframe below

,City,City Latitude,City Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Carlsbad,33.158093,-117.350597,Cafe Elysa,33.157190,-117.350444,Bakery
1,Carlsbad,33.158093,-117.350597,Gaia Gelato,33.159270,-117.350831,Ice Cream Shop
2,Carlsbad,33.158093,-117.350597,Naked Cafe,33.159075,-117.350506,Breakfast Spot
3,Carlsbad,33.158093,-117.350597,Choice Juicery,33.159605,-117.348978,Juice Bar
4,Carlsbad,33.158093,-117.350597,Las Olas Mexican Food,33.158707,-117.351569,Mexican Restaurant

In [14]:
# How many venues are there in each city?
sd_venues.groupby(["City"]).count()

,City Latitude,City Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
City,,,,,,
Carlsbad,100,100,100,100,100,100
Chula Vista,24,24,24,24,24,24
Coronado,15,15,15,15,15,15
Del Mar,43,43,43,43,43,43
El Cajon,20,20,20,20,20,20
Encinitas,28,28,28,28,28,28
Escondido,35,35,35,35,35,35
Imperial Beach,27,27,27,27,27,27
La Mesa,27,27,27,27,27,27
Lemon Grove,27,27,27,27,27,27
National City,46,46,46,46,46,46
Oceanside,55,55,55,55,55,55
Poway,4,4,4,4,4,4
San Diego,94,94,94,94,94,94
San Marcos,34,34,34,34,34,34
Santee,8,8,8,8,8,8
Solana Beach,46,46,46,46,46,46
Vista,48,48,48,48,48,48

In [15]:
# How many unique categories can be curated from all the returned venues?
print('There are {} unique categories.'.format(len(sd_venues['Venue Category'].unique())))
# Preview of unique categories
sd_venues['Venue Category'].unique()[:50]

There are 184 unique categories.

array(['Bakery', 'Ice Cream Shop', 'Breakfast Spot', 'Juice Bar',
       'Mexican Restaurant', 'American Restaurant', 'Café', 'Pizza Place',
       'Restaurant', 'Bar', 'Cocktail Bar', 'Massage Studio', 'Beach',
       'Italian Restaurant', 'Hotel', 'Resort', 'Coffee Shop',
       'Salon / Barbershop', 'Donut Shop', 'Boutique', 'Wine Bar',
       'Record Shop', 'Seafood Restaurant', 'Farmers Market', 'Speakeasy',
       'Gourmet Shop', 'Sushi Restaurant', 'Yoga Studio', 'Beer Store',
       'Asian Restaurant', 'Burger Joint', 'Shipping Store', 'Theater',
       'Music Venue', 'Pub', 'Frozen Yogurt Shop', 'Dive Bar',
       'Chinese Restaurant', 'Video Store', 'Convenience Store', 'Park',
       'Bank', 'Pilates Studio', 'Train Station', 'Sporting Goods Shop',
       'Flea Market', 'Bed & Breakfast', 'Brewery',
       'Gym / Fitness Center', 'Martial Arts School'], dtype=object)

In [22]:
# one hot encoding
one_hot_sd = pd.get_dummies(sd_venues[['Venue Category']], prefix = "", prefix_sep = "")

# add City column back to sd_venues dataframe
one_hot_sd['City'] = sd_venues['City']

# move City column to first column
fixed_columns = [one_hot_sd.columns[-1]] + list(one_hot_sd.columns[:-1])
one_hot_sd = one_hot_sd[fixed_columns]

print(f'There are {one_hot_sd.shape[0]} rows and {one_hot_sd.shape[1]} columns in the dataframe below')
one_hot_sd.head()

There are 681 rows and 185 columns in the dataframe below

,City,ATM,Accessories Store,American Restaurant,Arcade,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auto Workshop,...,Train Station,Turkish Restaurant,Vape Store,Video Game Store,Video Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wings Joint,Yoga Studio
0,Carlsbad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Carlsbad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Carlsbad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Carlsbad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Carlsbad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
# Grouping rows by city

one_hot_group = one_hot_sd.groupby(["City"]).mean().reset_index()

print(one_hot_group.shape)

one_hot_group

(18, 185)

,City,ATM,Accessories Store,American Restaurant,Arcade,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auto Workshop,...,Train Station,Turkish Restaurant,Vape Store,Video Game Store,Video Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wings Joint,Yoga Studio
0,Carlsbad,0.000000,0.000000,0.060000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,...,0.010000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.020000,0.000000,0.010000
1,Chula Vista,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Coronado,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Del Mar,0.000000,0.023256,0.069767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.023256,0.000000,0.000000
4,El Cajon,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,Encinitas,0.000000,0.000000,0.107143,0.000000,0.000000,0.035714,0.000000,0.035714,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.035714,0.000000,0.000000
6,Escondido,0.028571,0.000000,0.085714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028571,0.000000,0.000000
7,Imperial Beach,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.037037,0.000000,0.000000,0.000000,0.000000,0.000000,0.037037,0.000000
8,La Mesa,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.037037,0.000000,0.037037,0.000000,0.000000,0.037037
9,Lemon Grove,0.000000,0.000000,0.037037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,National City,0.000000,0.000000,0.000000,0.021739,0.000000,0.021739,0.021739,0.000000,0.021739,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.021739,0.000000,0.000000,0.021739,0.000000
11,Oceanside,0.000000,0.000000,0.054545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.036364,0.000000,0.000000,0.000000,0.000000,0.018182,0.000000,0.000000,0.000000,0.000000
12,Poway,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000
13,San Diego,0.000000,0.031915,0.031915,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.010638,0.000000,0.000000,0.000000,0.010638,0.000000,0.010638,0.000000,0.000000
14,San Marcos,0.000000,0.000000,0.029412,0.000000,0.000000,0.000000,0.029412,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,Santee,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.125000,0.000000,0.000000,0.000000,0.000000,0.000000
16,Solana Beach,0.000000,0.000000,0.043478,0.000000,0.021739,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,Vista,0.000000,0.000000,0.041667,0.000000,0.000000,0.020833,0.000000,0.020833,0.000000,...,0.000000,0.000000,0.000000,0.020833,0.000000,0.000000,0.000000,0.000000,0.020833,0.000000

In [27]:
# Taking the top 5 venue types for each city

num_top_venues = 5

for city in one_hot_group['City']:
    print("----"+city+"----")
    temp = one_hot_group[one_hot_group['City'] == city].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Carlsbad----
                 venue  freq
0  American Restaurant  0.06
1   Mexican Restaurant  0.06
2   Italian Restaurant  0.06
3                 Café  0.05
4                Beach  0.05


----Chula Vista----
                venue  freq
0                Park  0.08
1             Brewery  0.08
2  Italian Restaurant  0.08
3      Cosmetics Shop  0.08
4  Mexican Restaurant  0.08


----Coronado----
           venue  freq
0  Movie Theater  0.07
1          Hotel  0.07
2          Diner  0.07
3           Park  0.07
4          Motel  0.07


----Del Mar----
                 venue  freq
0   Italian Restaurant  0.07
1  American Restaurant  0.07
2   Mexican Restaurant  0.07
3   Seafood Restaurant  0.07
4                 Park  0.05


----El Cajon----
                       venue  freq
0         Mexican Restaurant  0.15
1  Middle Eastern Restaurant  0.05
2                        Bar  0.05
3         Chinese Restaurant  0.05
4             Clothing Store  0.05


----Encinitas----
                 venue  freq
0  American Restaurant  0.11
1          Coffee Shop  0.11
2                  Bar  0.07
3               Garden  0.04
4            Bookstore  0.04


----Escondido----
                 venue  freq
0          Coffee Shop  0.09
1  American Restaurant  0.09
2       Cosmetics Shop  0.09
3       Ice Cream Shop  0.06
4    French Restaurant  0.06


----Imperial Beach----
                  venue  freq
0  Fast Food Restaurant  0.11
1                   Bar  0.07
2            Sports Bar  0.04
3    Mexican Restaurant  0.04
4           Coffee Shop  0.04


----La Mesa----
                venue  freq
0  Mexican Restaurant  0.07
1         Yoga Studio  0.04
2     Doctor's Office  0.04
3  Chinese Restaurant  0.04
4      Clothing Store  0.04


----Lemon Grove----
                    venue  freq
0      Mexican Restaurant  0.11
1                    Café  0.07
2          Clothing Store  0.07
3          Sandwich Place  0.07
4  Thrift / Vintage Store  0.04


----National City----
                  venue  freq
0    Mexican Restaurant  0.07
1    Chinese Restaurant  0.07
2  Fast Food Restaurant  0.04
3        Sandwich Place  0.04
4         Grocery Store  0.04


----Oceanside----
                 venue  freq
0          Pizza Place  0.05
1  American Restaurant  0.05
2          Coffee Shop  0.05
3       Ice Cream Shop  0.05
4                  Bar  0.04


----Poway----
                    venue  freq
0  Furniture / Home Store  0.25
1           Big Box Store  0.25
2             Video Store  0.25
3        Basketball Court  0.25
4               Pet Store  0.00


----San Diego----
                venue  freq
0               Hotel  0.09
1         Coffee Shop  0.07
2      Clothing Store  0.04
3  Seafood Restaurant  0.04
4  Mexican Restaurant  0.03


----San Marcos----
                  venue  freq
0  Fast Food Restaurant  0.15
1                Bakery  0.09
2    Mexican Restaurant  0.06
3        Sandwich Place  0.06
4          Burger Joint  0.06


----Santee----
                venue  freq
0    Business Service  0.25
1  Mexican Restaurant  0.25
2      Baseball Field  0.12
3      Cosmetics Shop  0.12
4         Video Store  0.12


----Solana Beach----
                    venue  freq
0  Furniture / Home Store  0.11
1             Coffee Shop  0.07
2                     Bar  0.04
3     American Restaurant  0.04
4        Sushi Restaurant  0.04


----Vista----
                  venue  freq
0   American Restaurant  0.04
1         Deli / Bodega  0.04
2           Pizza Place  0.04
3  Fast Food Restaurant  0.04
4               Brewery  0.04

In [28]:
# A function to sort the venues in descending order

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [31]:
# Putting the top 5 venues for each city in a dataframe

num_top_venues = 5

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['City']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
sd_venues_sorted = pd.DataFrame(columns=columns)
sd_venues_sorted['City'] = one_hot_group['City']

for ind in np.arange(one_hot_group.shape[0]):
    sd_venues_sorted.iloc[ind, 1:] = return_most_common_venues(one_hot_group.iloc[ind, :], num_top_venues)

sd_venues_sorted

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
0,Carlsbad,Italian Restaurant,American Restaurant,Mexican Restaurant,Bar,Beach
1,Chula Vista,Italian Restaurant,Brewery,Mexican Restaurant,Park,Cosmetics Shop
2,Coronado,Bistro,Grocery Store,Movie Theater,Shipping Store,Bus Stop
3,Del Mar,Italian Restaurant,American Restaurant,Seafood Restaurant,Mexican Restaurant,Park
4,El Cajon,Mexican Restaurant,Italian Restaurant,Optical Shop,Motorsports Shop,Seafood Restaurant
5,Encinitas,Coffee Shop,American Restaurant,Bar,Italian Restaurant,Sporting Goods Shop
6,Escondido,Cosmetics Shop,American Restaurant,Coffee Shop,French Restaurant,Mexican Restaurant
7,Imperial Beach,Fast Food Restaurant,Bar,Italian Restaurant,Donut Shop,Burger Joint
8,La Mesa,Mexican Restaurant,Yoga Studio,Fast Food Restaurant,Sandwich Place,Rental Car Location
9,Lemon Grove,Mexican Restaurant,Clothing Store,Café,Sandwich Place,Construction & Landscaping
10,National City,Mexican Restaurant,Chinese Restaurant,Sandwich Place,Pizza Place,Tea Room
11,Oceanside,Pizza Place,American Restaurant,Ice Cream Shop,Coffee Shop,Train Station
12,Poway,Big Box Store,Video Store,Basketball Court,Furniture / Home Store,Dessert Shop
13,San Diego,Hotel,Coffee Shop,Seafood Restaurant,Clothing Store,Italian Restaurant
14,San Marcos,Fast Food Restaurant,Bakery,Burger Joint,Sandwich Place,Mexican Restaurant
15,Santee,Mexican Restaurant,Business Service,Cosmetics Shop,Video Store,Fast Food Restaurant
16,Solana Beach,Furniture / Home Store,Coffee Shop,Design Studio,American Restaurant,Seafood Restaurant
17,Vista,Mobile Phone Shop,Brewery,Deli / Bodega,American Restaurant,Ice Cream Shop

In [39]:
# set number of clusters
kclusters = 5

sd_grouped_clusters = one_hot_group.drop('City', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=42).fit(sd_grouped_clusters)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:18]

array([0, 0, 3, 0, 0, 0, 0, 4, 0, 4, 4, 0, 2, 0, 4, 1, 0, 4], dtype=int32)

In [38]:
# New dataframe that includes the cluster, as well as the top 5 venues per city
# add clustering labels

# Comment/uncomment below in order to get Cluster Labels - only run once!
# sd_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

sd_merged = df1

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
sd_merged = sd_merged.join(sd_venues_sorted.set_index('City'), on='City')

sd_merged["Cluster Labels"] = sd_merged["Cluster Labels"].replace(np.nan,0)
sd_merged = sd_merged.astype({"Cluster Labels": int})
sd_merged # Check the last columns!

,City,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
0,Carlsbad,33.158093,-117.350597,0,Italian Restaurant,American Restaurant,Mexican Restaurant,Bar,Beach
1,Chula Vista,32.640054,-117.084196,0,Italian Restaurant,Brewery,Mexican Restaurant,Park,Cosmetics Shop
2,Coronado,32.691520,-117.176695,3,Bistro,Grocery Store,Movie Theater,Shipping Store,Bus Stop
3,Del Mar,32.959489,-117.265315,0,Italian Restaurant,American Restaurant,Seafood Restaurant,Mexican Restaurant,Park
4,El Cajon,32.794773,-116.962527,0,Mexican Restaurant,Italian Restaurant,Optical Shop,Motorsports Shop,Seafood Restaurant
5,Encinitas,33.036987,-117.291982,0,Coffee Shop,American Restaurant,Bar,Italian Restaurant,Sporting Goods Shop
6,Escondido,33.121675,-117.081485,0,Cosmetics Shop,American Restaurant,Coffee Shop,French Restaurant,Mexican Restaurant
7,Imperial Beach,32.583944,-117.113085,4,Fast Food Restaurant,Bar,Italian Restaurant,Donut Shop,Burger Joint
8,La Mesa,32.772404,-117.029327,0,Mexican Restaurant,Yoga Studio,Fast Food Restaurant,Sandwich Place,Rental Car Location
9,Lemon Grove,32.742552,-117.031417,4,Mexican Restaurant,Clothing Store,Café,Sandwich Place,Construction & Landscaping
10,National City,32.678109,-117.099197,4,Mexican Restaurant,Chinese Restaurant,Sandwich Place,Pizza Place,Tea Room
11,Oceanside,33.195870,-117.379483,0,Pizza Place,American Restaurant,Ice Cream Shop,Coffee Shop,Train Station
12,Poway,32.962823,-117.035865,2,Big Box Store,Video Store,Basketball Court,Furniture / Home Store,Dessert Shop
13,San Diego,32.717421,-117.162771,0,Hotel,Coffee Shop,Seafood Restaurant,Clothing Store,Italian Restaurant
14,San Marcos,33.135021,-117.174330,4,Fast Food Restaurant,Bakery,Burger Joint,Sandwich Place,Mexican Restaurant
15,Santee,32.838383,-116.973917,1,Mexican Restaurant,Business Service,Cosmetics Shop,Video Store,Fast Food Restaurant
16,Solana Beach,32.990560,-117.269132,0,Furniture / Home Store,Coffee Shop,Design Studio,American Restaurant,Seafood Restaurant
17,Vista,33.200037,-117.242536,4,Mobile Phone Shop,Brewery,Deli / Bodega,American Restaurant,Ice Cream Shop

In [40]:
# Create SD map with clusters

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=10)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(sd_merged['Latitude'], sd_merged['Longitude'], sd_merged['City'], sd_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [43]:
# Cluster Labels = 0

sd_merged.loc[sd_merged['Cluster Labels'] == 0, sd_merged.columns[[0] + list(range(4, sd_merged.shape[1]))]]

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
0,Carlsbad,Italian Restaurant,American Restaurant,Mexican Restaurant,Bar,Beach
1,Chula Vista,Italian Restaurant,Brewery,Mexican Restaurant,Park,Cosmetics Shop
3,Del Mar,Italian Restaurant,American Restaurant,Seafood Restaurant,Mexican Restaurant,Park
4,El Cajon,Mexican Restaurant,Italian Restaurant,Optical Shop,Motorsports Shop,Seafood Restaurant
5,Encinitas,Coffee Shop,American Restaurant,Bar,Italian Restaurant,Sporting Goods Shop
6,Escondido,Cosmetics Shop,American Restaurant,Coffee Shop,French Restaurant,Mexican Restaurant
8,La Mesa,Mexican Restaurant,Yoga Studio,Fast Food Restaurant,Sandwich Place,Rental Car Location
11,Oceanside,Pizza Place,American Restaurant,Ice Cream Shop,Coffee Shop,Train Station
13,San Diego,Hotel,Coffee Shop,Seafood Restaurant,Clothing Store,Italian Restaurant
16,Solana Beach,Furniture / Home Store,Coffee Shop,Design Studio,American Restaurant,Seafood Restaurant

In [44]:
# Cluster Labels = 1

sd_merged.loc[sd_merged['Cluster Labels'] == 1, sd_merged.columns[[0] + list(range(4, sd_merged.shape[1]))]]

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
15,Santee,Mexican Restaurant,Business Service,Cosmetics Shop,Video Store,Fast Food Restaurant

In [45]:
# Cluster Labels = 2

sd_merged.loc[sd_merged['Cluster Labels'] == 2, sd_merged.columns[[0] + list(range(4, sd_merged.shape[1]))]]

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
12,Poway,Big Box Store,Video Store,Basketball Court,Furniture / Home Store,Dessert Shop

In [46]:
# Cluster Labels = 3

sd_merged.loc[sd_merged['Cluster Labels'] == 3, sd_merged.columns[[0] + list(range(4, sd_merged.shape[1]))]]

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
2,Coronado,Bistro,Grocery Store,Movie Theater,Shipping Store,Bus Stop

In [47]:
# Cluster Labels = 4

sd_merged.loc[sd_merged['Cluster Labels'] == 4, sd_merged.columns[[0] + list(range(4, sd_merged.shape[1]))]]

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue
7,Imperial Beach,Fast Food Restaurant,Bar,Italian Restaurant,Donut Shop,Burger Joint
9,Lemon Grove,Mexican Restaurant,Clothing Store,Café,Sandwich Place,Construction & Landscaping
10,National City,Mexican Restaurant,Chinese Restaurant,Sandwich Place,Pizza Place,Tea Room
14,San Marcos,Fast Food Restaurant,Bakery,Burger Joint,Sandwich Place,Mexican Restaurant
17,Vista,Mobile Phone Shop,Brewery,Deli / Bodega,American Restaurant,Ice Cream Shop